# Generated by Django 4.1.3 on 2022-11-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoService',
            fields=[
                ('client_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('massage_name', models.CharField(max_length=255)),
                ('service_date', models.DateField()),
                ('service_cashed_price', models.FloatField()),
            ],
            options={
                'db_table': 'dm_mgmt_conso_service',
                'managed': False,
            },
        ),
    ]
